dist: focal
language: python
python:
  - "3.11"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate


after_script:
  - coveralls

script:
  - black .
  - black --check .
  - flake8 .
#   - coverage run --source='user_profile,dashboard,search,view_profile,vibematch' manage.py test --settings=vibecheck.test_settings user_profile dashboard search view_profile vibematch --no-input --keepdb