dist: focal
language: python
python:
  - "3.11"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - black .
  - black --check .
  - flake8 .
  - coverage run manage.py 
#  - coverage run --source=mysite_swe1_app,polls manage.py test


after_script:
  - coveralls --service=github

deploy:
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  region: "us-east-1"
  app: "app_assignment2"
  env: "mysite_env"
  bucket_name: "elasticbeanstalk-us-east-1-905418363028"
  on:
    branch: master

