dist: focal
language: python
python:
  - "3.11"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - black .
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls --service=github
  